### ISSUE TITLE
[BUG] 1.36 I cannot click on the "exit game" button (By Dr.Chen)

### ISSUE THREAD

**Issue by Wandayu** [CryoVR/CryoVR_Vitrobot#11]
**Describe the Bug:**

I tried to click on the "exit game" button at the far right end - did not work. I have to click to "retrun to main menu", then "exit".

**Comment by SchubyDong** [comment]
This bug has been fixed

**Comment by smallelephant9516** [comment]
In our vitrobot version, this is still not fixed.

**Comment by Wandayu** [comment]
> In our vitrobot version, this is still not fixed.

Yes, I still cannot click the exit button in the right menu bar in version 1.38

**Comment by SchubyDong** [comment]
Bug fixed again, please try this function in the newest version

**Comment by SchubyDong** [comment]
10/14/2020 update, we have redesigned the logic of the exit button to make sure it works in different conditions

**Comment by smallelephant9516** [comment]
Solved in the 1.40 version of vitrobot
